### ISSUE TITLE
哪边科禁止上下滑动

### ISSUE THREAD

**Issue by GuilinSir** [wensefu/StackCardsView#3]

**Comment by GuilinSir** [comment]
哪边禁止上下滑动

**Comment by wensefu** [comment]
重写Adapter的getSwipeDirection方法，
如果只想左右滑动:
  @Override
    public int getSwipeDirection(int position) {
        
           return StackCardsView.SWIPE_LEFT | StackCardsView.SWIPE_RIGHT;
    }

**Comment by liuzhenxin111** [comment]
设置之后不行啊 还是能够上下滑动，

**Comment by wensefu** [comment]
上下滑动超过斜率时会认为是左右滑动。

**Comment by liuzhenxin111** [comment]
大神我能加你微信 吗？遇到了个问题。
咱们这个控件上面有个展位图。当有数据时展位图消失，现在有数据但是我从别的页面切回来。展位图显示了，咱们的卡片也在下面显示了。偶先的 啥原因啊

**Comment by liuzhenxin111** [comment]
大佬qq 2802035609  谢谢了

**Comment by SkyUnicorn** [comment]
仅仅重写Adapter的getSwipeDirection方法，实测无效。
用另一种方式可以实现，我debug调试，发现开启fastDismissAllowed后，滑动进的是都是fast的方法，我这里在自己的adapter中关闭isFastDismissAllowed，然后getDismissDirection方法设置左右（getSwipeDirection方法可以设置全部也可以设置左右，看个人需求了，设置左右感觉上下很生硬的卡主，不如设置全部，让它回弹），然后在StackCardsView控件内把DISMISS_FACTOR参数调低，我设置的是0.2f，用以替代fast滑动效果，基本能满足只左右滑动的需求。

**Comment by GuilinSir** [comment]
> 仅仅重写适配器的getSwipeDirection方法，实测无效。
> 用另一种方式可以实现，我调试调试，发现开启fastDismissAllowed后，滑动进的是都是快速的方法，我这里在自己的适配器中关闭isFastDismissAllowed，然后getDismissDirection方法设置左右（getSwipeDirection方法可以设置全部也可以设置左右，看个人需求了，设置左右感觉上下很生硬的卡主，不如设置全部，让它回弹），然后在StackCardsView控件内把DISMISS_FACTOR参数调低，我设置的是0.2F，用以替代快速滑动效果，基本能满足只左右滑动的需求。

厉害了老铁

**Comment by zhengjiashuo** [comment]
重写之后 把斜率干大点就好了 SwipeTouchHelper里的 这个参数SLOPE 这样完美解决
